# Generated by Django 4.1.5 on 2023-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(max_length=225, verbose_name='Event Time')),
                ('venue', models.CharField(max_length=225)),
                ('manager', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
